-- MySQL Script generated by MySQL Workbench
-- Wed Nov 16 20:31:47 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ibooks
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ibooks
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ibooks` DEFAULT CHARACTER SET utf8 ;
USE `ibooks` ;

-- -----------------------------------------------------
-- Table `ibooks`.`pessoaFisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ibooks`.`pessoaFisica` (
  `idpessoaFisica` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `dtNasc` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `nivelAcesso` INT NULL DEFAULT 0,
  PRIMARY KEY (`idpessoaFisica`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ibooks`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ibooks`.`categoria` (
  `idCategoria` INT NOT NULL,
  `nomeCategoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ibooks`.`Patrimonio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ibooks`.`Patrimonio` (
  `idPatrimonio` INT NOT NULL,
  `nome_patrimonio` VARCHAR(45) NOT NULL,
  `valor_patrimonio` DECIMAL(10,2) NOT NULL,
  `data_aquisicao` VARCHAR(45) NOT NULL,
  `numero_patrimonio` VARCHAR(45) NOT NULL,
  `image` VARCHAR(20) NULL,
  `categoria_idCategoria` INT NOT NULL,
  PRIMARY KEY (`idPatrimonio`),
  INDEX `fk_Patrimonio_categoria_idx` (`categoria_idCategoria` ASC) VISIBLE,
  CONSTRAINT `fk_Patrimonio_categoria`
    FOREIGN KEY (`categoria_idCategoria`)
    REFERENCES `ibooks`.`categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ibooks`.`editora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ibooks`.`editora` (
  `ideditora` INT NOT NULL,
  `nome_editora` VARCHAR(45) NULL,
  PRIMARY KEY (`ideditora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ibooks`.`idioma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ibooks`.`idioma` (
  `ididioma` INT NOT NULL,
  `idioma_nome` VARCHAR(45) NULL,
  PRIMARY KEY (`ididioma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ibooks`.`titulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ibooks`.`titulo` (
  `idtitulo` INT NOT NULL,
  `nome_titulo` VARCHAR(45) NOT NULL,
  `qtde_paginas_titulo` INT NOT NULL,
  `idioma_ididioma` INT NOT NULL,
  PRIMARY KEY (`idtitulo`),
  INDEX `fk_titulo_idioma1_idx` (`idioma_ididioma` ASC) VISIBLE,
  CONSTRAINT `fk_titulo_idioma1`
    FOREIGN KEY (`idioma_ididioma`)
    REFERENCES `ibooks`.`idioma` (`ididioma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ibooks`.`exemplar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ibooks`.`exemplar` (
  `idexemplar` INT NOT NULL,
  `numero_de_serie` VARCHAR(45) NOT NULL,
  `ISBN_10` VARCHAR(45) NOT NULL,
  `ISBN_13` VARCHAR(45) NOT NULL,
  `status` INT NOT NULL,
  `editora_ideditora` INT NOT NULL,
  `titulo_idtitulo` INT NOT NULL,
  PRIMARY KEY (`idexemplar`),
  INDEX `fk_exemplar_editora1_idx` (`editora_ideditora` ASC) VISIBLE,
  INDEX `fk_exemplar_titulo1_idx` (`titulo_idtitulo` ASC) VISIBLE,
  CONSTRAINT `fk_exemplar_editora1`
    FOREIGN KEY (`editora_ideditora`)
    REFERENCES `ibooks`.`editora` (`ideditora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exemplar_titulo1`
    FOREIGN KEY (`titulo_idtitulo`)
    REFERENCES `ibooks`.`titulo` (`idtitulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ibooks`.`parametrizacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ibooks`.`parametrizacao` (
  `idparametrizacao` INT NOT NULL,
  `nome_empresa` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idparametrizacao`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
